import { ShipMake } from "../objects/shipmakeup";

export const DEFAULT_MAKE: ShipMake = {
  name: "Dependable Dave",
  cost: 1500,
  slots: [
    { type: "cannon" },
    { type: "cannon" },
    { type: "cannon" },
    { type: "engine" },
    { type: "engine" },
  ],
  maxDamage: 50000,
  drag: 0.3,
  size: 20,
  lateralCrossSection: 1.7,
  repairCostScale: 0.007,
  weight: 1300,
};

export const MAKEDEFS: ShipMake[] = [
  {
    name: "Patroller",
    cost: 900,
    slots: [{ type: "cannon" }, { type: "engine" }],
    maxDamage: 20000,
    drag: 0.2,
    size: 12,
    lateralCrossSection: 2,
    repairCostScale: 0.004,
    weight: 300,
  },
  {
    name: "Hubris",
    cost: 800,
    slots: [{ type: "cannon" }, { type: "cannon" }, { type: "engine" }],
    maxDamage: 23000,
    drag: 0.25,
    size: 14,
    lateralCrossSection: 2.5,
    repairCostScale: 0.0055,
    weight: 700,
  },
  DEFAULT_MAKE,
  {
    name: "Wisp o' the Morning",

    cost: 1900,
    slots: [
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "engine" },
      { type: "engine" },
      { type: "engine" },
    ],
    maxDamage: 60000,
    drag: 0.32,
    size: 22,
    lateralCrossSection: 1.8,
    repairCostScale: 0.008,
    weight: 1550,
  },
  {
    name: "Jasper",
    cost: 2700,
    slots: [
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "engine" },
      { type: "engine" },
      { type: "engine" },
    ],
    maxDamage: 80000,
    drag: 0.34,
    size: 25,
    lateralCrossSection: 1.4,
    repairCostScale: 0.008,
    weight: 2100,
  },
  {
    name: "Marie Antoniette",
    cost: 3400,
    slots: [
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "engine" },
      { type: "engine" },
      { type: "engine" },
      { type: "engine" },
    ],
    maxDamage: 120000,
    drag: 0.37,
    size: 32,
    lateralCrossSection: 2.2,
    repairCostScale: 0.0105,
    weight: 4000,
  },
];
