import { ShipMake } from "../objects/shipmakeup";

export const DEFAULT_MAKE: ShipMake = {
  name: "Dependable Dave",
  cost: 2600,
  slots: [
    { type: "cannon" },
    { type: "cannon" },
    { type: "cannon" },
    { type: "engine" },
    { type: "engine" },
  ],
  maxDamage: 5000,
  drag: 0.3,
  size: 20,
  lateralCrossSection: 1.7,
  repairCostScale: 1.5,
  weight: 4000,
};

export const MAKEDEFS: ShipMake[] = [
  {
    name: "Patroller",
    cost: 900,
    slots: [{ type: "cannon" }, { type: "engine" }],
    maxDamage: 2000,
    drag: 0.2,
    size: 12,
    lateralCrossSection: 2,
    repairCostScale: 1.1,
    weight: 1000,
  },
  {
    name: "Queen Bee",
    cost: 1400,
    slots: [{ type: "cannon" }, { type: "cannon" }, { type: "engine" }],
    maxDamage: 2600,
    drag: 0.2,
    size: 16,
    lateralCrossSection: 1.4,
    repairCostScale: 1.3,
    weight: 2000,
  },
  {
    name: "Hubris",
    cost: 1700,
    slots: [
      { type: "cannon" },
      { type: "cannon" },
      { type: "engine" },
      { type: "engine" },
    ],
    maxDamage: 2400,
    drag: 0.25,
    size: 14,
    lateralCrossSection: 2.5,
    repairCostScale: 1.3,
    weight: 1800,
  },
  DEFAULT_MAKE,
  {
    name: "Wisp o' the Morning",
    cost: 4000,
    slots: [
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "engine" },
      { type: "engine" },
    ],
    maxDamage: 6000,
    drag: 0.32,
    size: 22,
    lateralCrossSection: 1.8,
    repairCostScale: 1.6,
    weight: 7000,
  },
  {
    name: "High Harpooner",
    cost: 5200,
    slots: [
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "engine" },
      { type: "engine" },
      { type: "engine" },
    ],
    maxDamage: 7500,
    drag: 0.28,
    size: 22,
    lateralCrossSection: 2.15,
    repairCostScale: 2,
    weight: 8500,
  },
  {
    name: "Jasper",
    cost: 7500,
    slots: [
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "engine" },
      { type: "engine" },
      { type: "engine" },
      { type: "engine" },
    ],
    maxDamage: 9000,
    drag: 0.34,
    size: 27,
    lateralCrossSection: 1.4,
    repairCostScale: 1.9,
    weight: 11000,
  },
  {
    name: "Marie Antoniette",
    cost: 12000,
    slots: [
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "cannon" },
      { type: "engine" },
      { type: "engine" },
      { type: "engine" },
      { type: "engine" },
      { type: "engine" },
    ],
    maxDamage: 12000,
    drag: 0.37,
    size: 33,
    lateralCrossSection: 2.2,
    repairCostScale: 2.5,
    weight: 16000,
  },
];
